# Generated by Django 6.0.1 on 2026-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='divider_type',
            field=models.CharField(choices=[('none', 'No dividers'), ('vertical', 'Vertical (left/right)'), ('horizontal', 'Horizontal (front/back)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='position',
            field=models.CharField(blank=True, help_text='Position in bin: left, right, front, back, etc.', max_length=20),
        ),
    ]
