# Generated by Django 6.0.1 on 2026-01-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bin_divider_type_inventoryitem_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Item Added'), ('update', 'Item Updated'), ('delete', 'Item Deleted'), ('move', 'Item Moved'), ('clear', 'Inventory Cleared')], max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('bin_code', models.CharField(max_length=10)),
                ('quantity_before', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_after', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
