# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='piece_weight_grams',
            field=models.FloatField(blank=True, help_text='Weight of one piece in grams', null=True),
        ),
    ]
